### ISSUE TITLE
No hay suficiente documentacion

### ISSUE THREAD

**Issue by melizamarquez** [gustavo9601/git-test-axiatech#1]
## Puedes sugerir cambios

El reporsitorio dejo de funcionar ? [ ]
No enctras algun archivo en el codigo [ ]
Otro [x ]

Especifica:

No se encontro suficiente documentacion

**Comment by gustavo9601** [comment]
Esta en proceso la documentacion

**Comment by gustavo9601** [comment]
Se finaliza ya que se esta trabajando

**Comment by gustavo9601** [comment]
Se cierra
